### ISSUE TITLE
Remove target dir

### ISSUE THREAD

**Issue by jnichols-wortech** [WorTech/Music-Crux#1]
It's best practice not to include build artifacts such as binaries. For Java this is things like .class and .jar files. I'd recommend removing the /target/ folder from git and updating the .gitignore file with something like: 

*.class
*.jar
/target/

**Comment by jnichols-wortech** [comment]
To clarify, I noticed it in `Music-Crux/API/discogs-api-consumption/` There's no .gitignore.

**Comment by ao10** [comment]
[Fixed](https://github.com/WorTech/Music-Crux/commit/1d7fe8436572f64f67a2dd83f232dcbce7672ecd)
